export const menu = <i className="fa-solid fa-bars"></i>
export const closeMenu = <i className="fa-solid fa-xmark"></i>
export const education = <i className="fa-solid fa-building-columns"></i>
export const interest = <i className="fa-solid fa-star"></i>
export const goals = <i className="fa-solid fa-crosshairs"></i>
export const javascript = <i className="fa-brands fa-js"></i>
export const html = <i className="fa-brands fa-html5"></i>
export const css = <i className="fa-brands fa-css3-alt"></i>
export const react = <i className="fa-brands fa-react"></i>
export const node = <i className="fa-brands fa-node"></i>
export const bootsrap = <i className="fa-brands fa-bootstrap"></i>
export const git = <i className="fa-brands fa-square-git"></i>
export const api = <i className="fa-solid fa-network-wired"></i>
export const php = <i className="fa-brands fa-php"></i>
export const email = <i className="fa-solid fa-envelope"></i>
export const github = <i className="fa-brands fa-github"></i>